# Generated by Django 3.1.2 on 2020-11-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='activade',
            field=models.IntegerField(default=None),
        ),
    ]
