# Generated by Django 3.1.2 on 2020-11-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_activade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='activade',
            field=models.IntegerField(default='0'),
        ),
    ]
