# Generated by Django 3.1.2 on 2020-11-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201118_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='id_user',
        ),
    ]
