# Generated by Django 3.1.2 on 2020-11-19 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bids_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='active',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
