# Generated by Django 3.1.2 on 2020-11-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlistings_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='active',
        ),
    ]
