# Generated by Django 3.1.2 on 2020-11-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_auctionlistings_activado'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='activado',
            field=models.IntegerField(default=None),
        ),
    ]
