# Generated by Django 3.1.2 on 2020-11-20 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlistings_activado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='activado',
        ),
    ]
