# Generated by Django 3.1.2 on 2020-11-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201119_2118'),
        ('auctions', '0014_remove_auctionlistings_activado'),
    ]

    operations = [
    ]
