# Generated by Django 3.1.2 on 2020-11-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_merge_20201119_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='activade',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='auction_active',
            field=models.IntegerField(default=0),
        ),
    ]
