# Generated by Django 3.1.2 on 2020-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20201123_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
