# Generated by Django 3.1.2 on 2020-11-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20201123_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='image',
            field=models.ImageField(blank=True, upload_to='path/', verbose_name='Label'),
        ),
    ]
