# Generated by Django 3.1.2 on 2020-12-02 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='bids',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WatchLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_auction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='auction_watch_list', to='auctions.auctionlistings')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_watch_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
