# Generated by Django 3.1.2 on 2020-12-08 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20201201_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
