# Generated by Django 3.1.2 on 2020-12-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auctionlistings_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to='auctions.user'),
        ),
    ]
