# Generated by Django 4.0.4 on 2022-09-27 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20201208_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='answer',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='watchlists',
            name='id_auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_watch_list', to='auctions.auctionlistings'),
        ),
        migrations.AlterField(
            model_name='watchlists',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watch_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
